main: com.massivecraft.creativegates.CreativeGates
name: CreativeGates
version: 1.2
softdepend: [PermissionsEx, Permissions, DimensionDoor, MultiVerse, WorldManager]
permissions:
 creativegates.*:
  children:
   creativegates.create: true
   creativegates.destroy: true
   creativegates.use: true
 creativegates.create:
  description: create gates
  default: true
 creativegates.destroy:
  description: destroy gates
  default: true
 creativegates.use:
  description: use gates
  default: true